"use client";

import { useState, useEffect, useRef, useCallback, useTransition } from "react";
import { useRouter } from "next/navigation";
import LifecycleReport from "./LifecycleReport";
import DeleteAuditButton from "./DeleteAuditButton";
import type {
  LifecycleStageCount,
  AuditInsight,
  OwnerAssignmentStats,
} from "@/lib/hubspot/portal-analyzer";

interface Props {
  auditId: string;
  capturedAt: string | null;
  insightsGeneratedAt: string | null;
  contacts: LifecycleStageCount[];
  companies: LifecycleStageCount[];
  totalContacts: number;
  totalCompanies: number;
  totalDeals: number;
  totalTickets: number;
  lifecycleWorkflows: string[];
  ownerStats?: OwnerAssignmentStats;
  insights: AuditInsight[];
  hasLifecycleStats: boolean;
}

export default function AuditDetailClient({
  auditId,
  capturedAt,
  insightsGeneratedAt,
  contacts,
  companies,
  totalContacts,
  totalCompanies,
  totalDeals,
  totalTickets,
  lifecycleWorkflows,
  ownerStats,
  insights,
  hasLifecycleStats,
}: Props) {
  const router = useRouter();
  const [isFetching, setIsFetching] = useState(false);
  const [genError, setGenError] = useState("");
  const [isPending, startTransition] = useTransition();
  const hasAutoGenerated = useRef(false);

  // Combined loading state: true while API is in-flight OR while router refresh is pending
  const isGenerating = isFetching || isPending;

  const handleGenerate = useCallback(async () => {
    setIsFetching(true);
    setGenError("");
    try {
      const res = await fetch(`/api/audits/${auditId}/insights`, { method: "POST" });
      if (!res.ok) {
        const d = (await res.json()) as { error?: string };
        throw new Error(d.error ?? "Error al generar insights");
      }
      startTransition(() => {
        router.refresh();
      });
    } catch (e) {
      setGenError(e instanceof Error ? e.message : "Error desconocido");
    } finally {
      setIsFetching(false);
    }
  }, [auditId, router]);

  // Auto-generate on mount if no insights exist and there is data to analyze
  useEffect(() => {
    if (insights.length === 0 && hasLifecycleStats && !hasAutoGenerated.current) {
      hasAutoGenerated.current = true;
      handleGenerate();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <div className="flex-1 flex flex-col overflow-hidden">
      {/* ── Contenido ──────────────────────────────────────────────────────── */}
      <div className="flex-1 overflow-y-auto px-8 py-6">
        <div className="space-y-6">

          {/* Cabecera de sección */}
          <div className="flex items-start justify-between gap-4">
            <div>
              <h2 className="text-base font-semibold text-white mb-0.5">
                Distribución por ciclo de vida
              </h2>
              <p className="text-sm text-gray-500">
                Cómo están distribuidos los contactos y empresas en cada etapa del funnel al momento de la captura.
              </p>
            </div>
            {isGenerating ? (
              <p className="text-xs text-purple-400 shrink-0 mt-1 animate-pulse">
                Analizando portal con IA...
              </p>
            ) : insightsGeneratedAt ? (
              <p className="text-xs text-gray-600 shrink-0 mt-1">
                Insights generados el {insightsGeneratedAt}
              </p>
            ) : null}
          </div>

          {/* Error */}
          {genError && (
            <div className="px-4 py-3 rounded-lg bg-red-500/10 border border-red-500/20 text-sm text-red-400">
              {genError}
            </div>
          )}

          {!hasLifecycleStats ? (
            <div className="flex items-center justify-center h-40 rounded-xl bg-gray-900 border border-gray-800 text-gray-500 text-sm">
              No hay datos de ciclo de vida en esta auditoría.
            </div>
          ) : (
            <LifecycleReport
              contacts={contacts}
              companies={companies}
              totalContacts={totalContacts}
              totalCompanies={totalCompanies}
              totalDeals={totalDeals}
              totalTickets={totalTickets}
              lifecycleWorkflows={lifecycleWorkflows}
              ownerStats={ownerStats}
              insights={insights}
              isGenerating={isGenerating}
            />
          )}

        </div>
      </div>

      {/* ── Footer: ejecución capturada ─────────────────────────────────────── */}
      <div className="px-8 py-3 border-t border-gray-800 flex items-center justify-between gap-4 shrink-0">
        <p className="text-xs text-gray-500">
          {capturedAt
            ? <>Datos capturados el <span className="text-gray-400">{capturedAt}</span></>
            : "Sin datos capturados"
          }
        </p>
        <DeleteAuditButton auditId={auditId} />
      </div>
    </div>
  );
}
