// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // (directUrl NO es una opción de prisma.config — solo url/shadowDatabaseUrl.
    //  Estaba acá por el scaffold generado; DIRECT_URL ni siquiera está en .env,
    //  era un no-op que además rompía el type-check.)
  },
});
